### ISSUE TITLE
Git Clone Fails: Permission Denied

### ISSUE THREAD

**Issue by cmschube** [elliotkillick/qvm-create-windows-qube#1]
[user@disp6703 ~]$ git clone git@github.com:elliotkillick/qvm-create-windows-qube
Cloning into 'qvm-create-windows-qube'...
The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com,140.82.114.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[user@disp6703 ~]$

**Comment by elliotkillick** [comment]
Fixed in 656483fd869ec1b7e34a33828931f4d91714ba53.
