### ISSUE TITLE
SSL Error 104

### ISSUE THREAD

**Issue by francuss** [elliotkillick/qvm-create-windows-qube#10]
![20200302_181245](https://user-images.githubusercontent.com/22216941/75718641-12595580-5cb2-11ea-9c22-4de638345e77.jpg)

The uploaded photo of dom0 terminal show some SSL error and GPG issue.

When installation was tried there were some internet connection issues.

But trying again does not work, apparently because windows-mgmt already exists. Should I try to delete it and try again? Or what?
Many thanks

**Comment by elliotkillick** [comment]
I too have received this error from time to time when downloading from that Microsoft server. Seems to be an error on their end. Happens relatively rarely though.

I will add a loop to attempt the download again a few seconds after curl returns an error code to mitigate this issue.

For now, just do what you suggested and delete `windows-mgmt` then run `install.sh` again.

**Comment by elliotkillick** [comment]
Fixed in 4c9b57f4c9ef14e4acf91d4d1dec70a57651b8ef.
