### ISSUE TITLE
Windows 10 Pro: No window showing anymore after successful installation 

### ISSUE THREAD

**Issue by heinrich-ulbricht** [elliotkillick/qvm-create-windows-qube#16]
I'm not sure where I should start debugging this.

I followed the installation instructions and installed Windows 10 Pro. Everything went well. I also got the expected errors regarding Qubes Windows Utils, .NET etc. During the installation I could see the Windows 10 UI, could see the reboots. All good. Then the installation finished with a success message:

![image](https://user-images.githubusercontent.com/3469970/91670478-380ace80-eb1e-11ea-97f8-27c50d326aeb.png)

And now I have no UI anymore. I can start the Windows 10 VM. In the Qubes Domain Widget I see the VM running and consuming CPU. I can start programs from the start menu and see the hard drive LED blink and CPU usage go up for the Windows VM.

But I see no actual window to interact with. Nothing opens.

Does this point to a specific problem? How would I diagnose it? Any hints are appreciated. I just need a window to click...

**Comment by elliotkillick** [comment]
Yes, this has been a long-standing issue with QWT. Luckily, it's an easy fix. You can find it documented in the README under "Known QWT Issues".

But, basically just do:
`qvm-features windows-10 gui 1`

After that, all you have to do is boot the Windows machine up again!

**Comment by heinrich-ulbricht** [comment]
You mean this one:

> All OSs:
> 
>     No Windows display when Qubes GUI driver is not installed
>         Any OS other than Windows 7/Windows Server 2008 R2 does not support Qubes GUI driver
>         Temporary fix: Run qvm-features <windows_qube> gui 1 to make the display show up after Windows qube creation is complete
> 

Reading it again it's now obvious to me that this means "Windows 10 does not support Qubes GUI driver -> thus no window is displayed -> thus need to set gui 1 after installation which will fix it". It wasn't this clear to me reading it the first time.

It works now and I'm very happy :) Thank you for the quick answer!

**Comment by heinrich-ulbricht** [comment]
@elliotkillick Before I open a new ticket... is seamless mode expected to work with Windows 10 and the gui=1 configuration? Because it doesn't.

**Comment by elliotkillick** [comment]
Unfortunately, there is no support for seamless mode past Windows 7 due to newer OSs requiring a WDDM video driver as opposed to an XPDM one.

More info:
https://groups.google.com/d/msg/qubes-devel/aCCGpYysZTQ/v1F-koISEAAJ
