### ISSUE TITLE
SSL: public key does not match pinned public key

### ISSUE THREAD

**Issue by cm157** [elliotkillick/qvm-create-windows-qube#18]
I followed the instructions up to step 4 for installation. Once I executed the step 4 command in dom0 _chmod +x install.sh && ./install.sh_ I get stuck at a loop saying it has failed to download windows due to public key not matching the pinned one will retry in 10 seconds (loop$ Can anyone advise me in noob friendly way what possible cause of problem is and how I might fix it? I followed the instructions verbatim and I am running Qubes 4.0.3 with all available updates installed. 

Thanks

**Comment by michaljenicek** [comment]
I have the exact same problem, I used to use your tool several months ago and it worked fine, but now I am also stuck at this loop.

**Comment by jeffry-james** [comment]
I have the exact same problem. Would be nice If you could fix it, I am new to Qubes OS and your script was my hope :-)

**Comment by windgmbh** [comment]
This issue should be fixed by #22

**Comment by elliotkillick** [comment]
The fix has been merged! Thanks again, @windgmbh.
