### ISSUE TITLE
Intall.sh File Emptied Upon Transfer To Dom0

### ISSUE THREAD

**Issue by mcertini** [elliotkillick/qvm-create-windows-qube#2]
In following the instructions given in the main page of this site I completed the following instruction:

qvm-run -p --filter-escape-chars --no-color-output untrusted "cat  '/home/install.sh'" > install.sh

When doing an ls in Dom0, I could see the file was copied, though when I went into the file all of the contents were gone.  To view the contents of the file I used nano intall.sh.  I then did stat install.sh for the file in Dom0 as well as the file in the untrusted VM.  In Dom0 the file size is 0 whereas the file size in untrusted is 3772.  I have a 1.4M print-screen (jpg) of this but cannot attach it to this message.  I am getting an error message in the github website stating "Something went really wrong, and we cannot process that file"

**Comment by elliotkillick** [comment]
It looks like you specified `/home/install.sh` instead of `/home/Downloads/install.sh`. Try that instead. That path should go to wherever the file is located on the `untrusted` domain.

**Comment by elliotkillick** [comment]
Assuming this is solved due to no response.
