### ISSUE TITLE
Incorporate Disassembler0's Win10-Initial-Setup-Script

### ISSUE THREAD

**Issue by iamahuman** [elliotkillick/qvm-create-windows-qube#20]
Although there's a lot of overlap, perhaps we can mine a few things from there.

https://github.com/Disassembler0/Win10-Initial-Setup-Script

**Comment by elliotkillick** [comment]
@fepitre has already done this work (thanks!). However, as you said there is a lot of overlap so I don't think just dropping the whole thing in there is what we want to do. Also, I think it would be best to include the script as a Git submodule @fepitre if we do decide to include it. I just really don't like the way including that script locally makes the code language meter on GitHub say this project is over 85% PowerShell. I do put these projects on my resume so I would like the code language meter be an accurate representation of what it's actually written in.

Also, @iamahuman I must ask why this script in particular considering there are tons just like this.

Closing in favor of https://github.com/elliotkillick/qvm-create-windows-qube/issues/17. Please discuss all scripts further there.

**Comment by iamahuman** [comment]
@elliotkillick Perhaps the issue title was phrased in a misleading way.

By "incorporate" I meant to extract its knowledge of kill switches into this project, not bundle the script as a whole.

Anyway the script is no longer maintained so I don't think there's much to be done here.
