### ISSUE TITLE
Curl ISO Download: Public Key mismatch

### ISSUE THREAD

**Issue by winnduu** [elliotkillick/qvm-create-windows-qube#23]
After following the instructions in the repository, the script tries to download Windows 7 from official sources, but curl fails to do so because the SSL PubKey does not match the pinned one. It endlessly tries it again in a 10 second loop.

**Comment by winnduu** [comment]
If further information is needed and/or useful, dont hesitate to contact me!

**Comment by windgmbh** [comment]
This is a duplicate of issue #18 and should be resolved by the pull request #21 that has not been merged yet.
Furthermore I may point out that there is a [refractoring](https://qubes-os.discourse.group/t/r4-1-qvm-create-windows-qube/1875) of `qvm-create-windows-qube` going on.

**Comment by elliotkillick** [comment]
@windgmbh is correct (except the PR is acutally #22). The fix has now been merged! Closing this issue.
