### ISSUE TITLE
Windows 10 Professional QWT Install Issue (Private Volume Error)

### ISSUE THREAD

**Issue by cbmiller2610** [elliotkillick/qvm-create-windows-qube#25]
Not sure if this is better reported on the community forums or elsewhere, but figured I'd start here. 

QWT seems to need to create a "private volume" during the install process, and it is failing to format the disk (see screenshot).  Going to D:\ in explorer confirms that the volume is un-formatted.

This is on Windows 10 Pro 20H2, build 19042.631.

![Screenshot_2021-04-27_17-24-45](https://user-images.githubusercontent.com/7013753/116316367-d3bd0f00-a77f-11eb-8169-f542530a9735.png)

**Comment by elliotkillick** [comment]
This is a known issue in Qubes Windows Tools (not this project directly). Please see the [README](https://github.com/elliotkillick/qvm-create-windows-qube#qubes-windows-tools-known-issues).
