### ISSUE TITLE
command is not executed in dom0

### ISSUE THREAD

**Issue by Max079** [elliotkillick/qvm-create-windows-qube#26]
when I enter the command `qvm-run -p --filter-escape-chars --no-color-output <qube_script_is_located_on> "cat '/home/user/Downloads/install.sh'" > install.sh`  in `dom0` to copy `install.sh` to `dom0`, it doesn't work.

**Comment by blatchard** [comment]
I have been trying to use this repository today and that command worked fine, make sure that you only put the appVM name (don't include the <>) and that install.sh is actually in /home/user/Downloads/ in that same appVM.

**Comment by Max079** [comment]
I did the command exactly like this: `qvm-run -p --filter-escape-character - no-color output not trustworthy" cat '/home/user/Downloads/install.sh' "> install.sh` but it comes no error message and nothing happens. I did it exactly as in the instructions up to go 2.

**Comment by Max079** [comment]
I did the command exactly like this: `qvm-run -p --filter-escape-chars --no-color-output untrusted "cat '/home/user/Downloads/install.sh'" > install.sh` but it comes no error message and nothing happens. I did it exactly as in the instructions up to go 2.

**Comment by blatchard** [comment]
:/ apart from my qube being a different name, I did it identically to how you have just written it.  I'm sorry, but I can't be any help.  It does sound like an issue with your dom0 and not this repo though (although I had other issues with this repo when running the script in dom0).  Have you tried with another, self made, text file to see if it works for you? Maybe you could try that without the two additional arguments just to check its functional?

**Comment by Max079** [comment]
What does the `/user` stand for before `/Downloads` and after ` /home` ?

**Comment by blatchard** [comment]
@Max079 when you are referencing a file or directory of <name_of_vm> from either another vm or dom0 or from root in the <name_of_vm> , the path is always the full path from root.  In every VM (not dom0) the username is "user" by default, so the path in all vms to any of the user directories is /home/user/* .  the only place this is different is in dom0 where it will be /home/<your_qubes_username>/*

**Comment by blatchard** [comment]
> I did the command exactly like this: `qvm-run -p --filter-escape-chars --no-color-output untrusted "cat '/home/user/Downloads/install.sh'" > install.sh` but it comes no error message and nothing happens. I did it exactly as in the instructions up to go 2.

you did run this from a dom0 terminal right?

If you cannot run the command -> qvm-run -p untrusted "cat '/home/user/Downloads/[some_test_txt_file]'" > [some_test_text_file] from a dom0 terminal on a test text file you put in 'untrusted' qube, then its possible you may have deleted some qubes dependency files from the parent templateVM when uninstalling something else from its templateVM.   see this page: <br /><br /><a href="https://github.com/Qubes-Community/Contents/blob/master/docs/customization/removing-templatevm-packages.md">https://github.com/Qubes-Community/Contents/blob/master/docs/customization/removing-templatevm-packages.md</a>

**Comment by Max079** [comment]
I tried a text file that I had created myself, `Hello Man`, with the command `qvm-run -p untrusted "cat" /home/users/Downloads/Hello Man '" > Hello Man` and then the error came up  `qvm-run: unrecognized arguments: Man`

**Comment by Max079** [comment]
but that means that it should actually work.

**Comment by blatchard** [comment]
hi @Max079 the cat should not have double quotes on both sides, only infront of it as it is closed before the greater-than sign  "cat '/home/users/Downloads/TEXT-FILE '"  .  Also in the official Qubes OS documentation (found here: <a href="https://www.qubes-os.org/doc/copy-from-dom0/">https://www.qubes-os.org/doc/copy-from-dom0</a> ) you can see, it only uses one set of single quotes, not the set of double quotes and the set of single quotes as in this repo. qvm-run -p is a shorter way of writing --pass-io according to this document <a href="https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-run.html">https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-run.html</a></br>Also rename the test file to hello-man as I don't know how qvm-run -p handles spaces.

For the sake of knowing I made a test file called "test-text.txt" in the Downloads folder of untrusted.  I then ran 2 commands from dom0 and after opening the test file in dom0 deleted before using the other command. Both produced the file in ~/ directory of dom0.

qvm-run -p untrusted 'cat /home/user/Downloads/test-text.txt' > test-text.txt
qvm-run -p untrusted "cat '/home/user/Downloads/test-text.txt'" > test-text.txt

I also noticed you put /home/**users**/Downloads where it is always /home/**user**/Downloads. I hope this helps.

**Comment by elliotkillick** [comment]
Yes, just be careful to get all the quotes.

Note that the `--filter-escape-chars --no-color-output` flags are for removing terminal escape sequences which could be used to [hide what the contents of the script actually are](https://ma.ttias.be/terminal-escape-sequences-the-new-xss-for-linux-sysadmins/) when the `cat` command (or some other commands) are run on it. This is to ensure integrity of the script in the code review which is the next step in the installation process. Of course, one should never run code in the ultimately trusted `dom0` without first double-checking what is being run.

Thank you for the help, @blatchard!
