### ISSUE TITLE
Create Windows 10 qube

### ISSUE THREAD

**Issue by Max079** [elliotkillick/qvm-create-windows-qube#27]
I execute the command:
`./qvm-create-windows-qube.sh -n sys-firewall -oyp firefox,notepadplusplus,office365proplus -i win10x64.iso -a win10x64-pro.xml work-win10` 
but the following error message appears:
`File not found in windows-mgmt:/home/user/Documents/qvm-create-windows-qube/windows-media/isos: win10x64.iso`

Am I doing something wrong, or have I forgotten an intermediate step. am grateful for any help :-)

**Comment by elliotkillick** [comment]
As it says in the `README` and during installation, you must first download the Windows ISO you desire with the `download-windows.sh` script from official Microsoft servers. It's a pretty big download, so it may take some time.
