### ISSUE TITLE
win10x64.iso does not download

### ISSUE THREAD

**Issue by Max079** [elliotkillick/qvm-create-windows-qube#28]
I enter the command: `./download-windows.sh win10x64`

but then I get the error message: `Microsoft does not allow automatic downloading of this Windows media, so please download it manually here: https://www.microsoft.com/en-us/software-download/windows10ISO (Don't forget to verify it afterwards)`

then I tried to download the ISO from the official Microsoft site: `https://www.microsoft.com/en-us/software-download/windows10ISO` , but the download always stops.

is the problem with Microsoft or am I doing something wrong?

**Comment by elliotkillick** [comment]
The issue must be on your end because it has worked for everyone else just fine (I also just tested it myself). All you have to do is open that URL in a web browser and click through the prompts to start the download. Make sure you have a stable internet connection.

**Comment by Max079** [comment]
for me the download always stops at 1.8GB out of 5.4GB

**Comment by m-dhooge** [comment]
Late follow-up: the default private storage size is 2.0 GB. You have to increase this value in order to finish the download!
