### ISSUE TITLE
Qubes 4.0: Unable to make script work properly: GPG issues

### ISSUE THREAD

**Issue by CorshiaSey** [elliotkillick/qvm-create-windows-qube#29]
https://groups.google.com/g/qubes-users/c/vXDnBvjr6GA?pli=1

Relevant terminal logs linked within. Any help in getting a windows10 qube working would be appreciated. 

Problem seems to be that qvm-create-windows-qube in dom0 doesn't pop.

**Comment by CorshiaSey** [comment]
New Logs below. Work around appears to be: set netvm to sys-firewall as well as dom0 update to sys-firewall in Qubes global settings.

[user@dom0 ~]$ chmod +x install.sh && ./install.sh
[i] Creating windows-mgmt...
[i] Increasing storage capacity of windows-mgmt...
[i] Starting fedora-32...
[i] Installing package dependencies on fedora-32...
Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)
Last metadata expiration check: 0:09:31 ago on Wed Aug  4 11:27:47 2021.
Package genisoimage-1.1.11-44.fc32.x86_64 is already installed.
Package geteltorito-0.6-11.fc32.noarch is already installed.
Package datefudge-1.23-1.fc32.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[i] Shutting down fedora-32...
[i] Starting windows-mgmt...
[i] Cloning qvm-create-windows-qube GitHub repository...
Cloning into 'qvm-create-windows-qube'...
[i] Please check for a "Good signature" from GPG (Verify it out-of-band if necessary)...
gpg: Signature made Sat Nov 30 02:48:44 2019 EST
gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
gpg: Good signature from "Elliot Killick <elliotkillick@zohomail.eu>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 018F B9DE 6DFA 13FB 18FB  5552 F9B9 0D44 F83D D5F2
[i] Remember to download the desired version(s) of Windows using download-windows.sh in the windows-mgmt qube...
Usage: /home/user/Documents/qvm-create-windows-qube/windows-media/isos/download-windows.sh <windows_media>...

Download specified list of Windows media.

Specify "all", or one or more of the following Windows media:
  win7x64-ultimate
  win81x64
  win10x64
  win81x64-enterprise-eval
  win10x64-enterprise-eval
  win10x64-ltsc-eval
  win2008r2
  win2012r2-eval
  win2016-eval
  win2019-eval

Important: The direct ISO downloads listed here are not necessarily subject to being updated and it is therefore recommended that the source referenced above each curl command in the script is checked to see if a newer version is available. Contributions regarding updates for these links are welcome.
[i] Shutting down windows-mgmt...
[i] Air gapping windows-mgmt...
[i] Installing Qubes Windows Tools...
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)
Fedora 25 - x86_64 - Updates                    6.6 MB/s |  24 MB     00:03    
Fedora 25 - x86_64                              9.0 MB/s |  50 MB     00:05    
Qubes Dom0 Repository (updates)                 2.5 MB/s | 2.9 MB     00:01    
determining the fastest mirror (14 hosts).. done.--  B/s |   0  B     --:-- ETA
Qubes Templates repository                      4.1 kB/s | 5.9 kB     00:01    
Last metadata expiration check: 0:00:01 ago on Wed Aug  4 11:38:54 2021.
Dependencies resolved.
================================================================================
 Package                 Arch       Version        Repository              Size
================================================================================
Installing:
 qubes-windows-tools     noarch     4.0.1-3        qubes-dom0-current      16 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 16 M
Installed size: 18 M
DNF will only download packages for the transaction.
Downloading Packages:
qubes-windows-tools-4.0.1-3.noarch.rpm          2.6 MB/s |  16 MB     00:05    
--------------------------------------------------------------------------------
Total                                           2.5 MB/s |  16 MB     00:06     
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Qubes OS Repository for Dom0                     21 MB/s |  25 kB     00:00    
Dependencies resolved.
================================================================================
 Package                  Arch        Version      Repository              Size
================================================================================
Installing:
 qubes-windows-tools      noarch      4.0.1-3      qubes-dom0-cached       16 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 16 M
Installed size: 18 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : qubes-windows-tools-4.0.1-3.noarch                          1/1 
  Verifying   : qubes-windows-tools-4.0.1-3.noarch                          1/1 

Installed:
  qubes-windows-tools.noarch 4.0.1-3                                            

Complete!
[i] Copying qvm-create-windows-qube main program to Dom0...
[+] Installation complete!
[user@dom0 ~]$ qvm-create-windows-qube -n sys-firewall -oyp firefox,notepadplus,office365proplus -i win10x64-ltsc-eval.iso -a win10x64-ltsc-eval.xml work-win10

**Comment by CorshiaSey** [comment]
Suggestion for improvements to script: Have install script download the key and import it manually instead of using the keyserver which appears to be case. Suggestion credited to thierry, the privacybeast guy who helped me troubleshoot this some.

**Comment by CorshiaSey** [comment]
Workaround appears to be: set netvm to sys-firewall as well as dom0update to sys-firewall in Qubes Global Settings.

Workaround: fix the install.sh script to download https://keys.openpgp.org/vks/v1/by-fingerprint/018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2 and import manually instead of attempting to do --recv-key which will not work over AppVMs other than whonix based appvms using sys-whonix as netvm.

**Comment by elliotkillick** [comment]
Yes, the `install.sh` script uses the global default NetVM which is `sys-firewall` by default unless it was manually changed, like in your case, to `sys-whonix`. Note that you can specify a NetVM for the `install.sh` script to use by as follows: `./install.sh sys-firewall`

I have no issue downloading the key from `keys.openpgp.org` over Tor using `gpg`. Perhaps you just got unlucky with a bad IP which they blocked or maybe the connection to a Tor node just dropped for a moment?

The reason the `--recv-keys` option is being used is in an attempt to reduce the trust that is placed in GitHub as [Qubes distrusts the infrastructure](https://www.qubes-os.org/faq/#what-does-it-mean-to-distrust-the-infrastructure). The user is asked to review the contents of `install.sh` so which contains the key to download so hopefully that is enough.

The issue here is really with the Tor network dropping that request or an exit node IP being blocked. If it's going to potentially cause problems, I plan to just bring the key into the local repo as suggested. The aforementioned security benefits are questionable and it's really just temporary thing until this project is delivered in packaged form, see: #11

By the way, please enclose your logs with three backticks (`) to make them easier to read.

**Comment by elliotkillick** [comment]
Fixed in https://github.com/elliotkillick/qvm-create-windows-qube/commit/d2dba0b6065cbae6eb419aa8ae0aeacc474d7581.
