### ISSUE TITLE
error message"curl: (90) SSL: public key does not match pinned public key!" and can not download the windows7 iso

### ISSUE THREAD

**Issue by guazi111** [elliotkillick/qvm-create-windows-qube#3]
I got messages as"curl: (90) SSL: public key does not match pinned public key!"
my system version is qubesos_4.0.2_rc3
error log:

[i] Cloning qvm-create-windows-qube GitHub repository...
Cloning into 'qvm-create-windows-qube'...
[i] Please check for a good PGP signature (Verify it out-of-band if necessary)...
gpg: Signature made Sat Nov 30 02:48:44 2019 EST
gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
gpg: Good signature from "Elliot Killick <elliotkillick@zohomail.eu>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 018F B9DE 6DFA 13FB 18FB  5552 F9B9 0D44 F83D D5F2
[i] Downloading Windows 7 (Other versions of Windows can be downloaded later by using download-windows.sh)...
[i] Downloading Windows media from Microsoft servers...
[i] Downloading Windows 7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (90) SSL: public key does not match pinned public key!

**Comment by elliotkillick** [comment]
I do not get this error when downloading the Windows 7 ISO.

The ISO is sourced from `download.microsoft.com` and after doing a `curl -v download.microsoft.com` here's the certificate I get:
```
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; OU=Microsoft Corporation; CN=download.microsoft.com
*  start date: Oct 29 18:37:25 2018 GMT
*  expire date: Oct 29 18:37:25 2020 GMT
*  subjectAltName: host "download.microsoft.com" matched cert's "download.microsoft.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.
```

If you're getting a different certificate then I believe your connection is being intercepted. This may be the case in some enterprise networks or countries where they do TLS interception.

In any case, it should be possible to verify the integrity of the downloaded ISO by the checksum verification that takes place afterwards. I recommend removing `--pinnedpublickey <key>` from the `curl` command in `download-windows.sh` and to make sure the ISO verifies successfully with an `OK` message once downloaded.

That is indeed my PGP key which is good.

**Comment by elliotkillick** [comment]
Assuming solved due to no reply.
