### ISSUE TITLE
download-windows.sh script not found

### ISSUE THREAD

**Issue by cm157** [elliotkillick/qvm-create-windows-qube#31]
I followed all instructions up to step 5. No errors in dom0. I gave the windows-mgmt vm network access (i accept risk) and then in terminal for that vm i typed windows-media/isos/download-windows.sh 

![image](https://user-images.githubusercontent.com/71204465/132122211-46d63132-7fff-4b6e-bda1-ee1efbd1cae2.jpeg)

Please help . I have been reading this over and over trying find what i missed and i cant figure out whats wrong

**Comment by elliotkillick** [comment]
The `windows-media/isos/download-windows.sh` path provided in the `README` was referring to where that file is located relative to this Git/GitHub repo. But for clarity, I should've had it point to where it was relative to when you first open a terminal in `windows-mgmt`. I've now updated the `README` with the full path to `download-windows.sh` inside `windows-mgmt` to remove any confusion: `/home/user/Documents/qvm-create-windows-qube/windows-media/isos/download-windows.sh`

Before re-attempting, please first run this command from within `windows-mgmt` to get all the latest updates: `cd ~/Documents/qvm-create-windows-qube && git pull`
