### ISSUE TITLE
Suggestion: Add instruction how to update script properly

### ISSUE THREAD

**Issue by baack** [elliotkillick/qvm-create-windows-qube#44]
Suggestion: Add instruction how to update script properly. You make some useful commits, the instruction required in readme about the proper way to Update the script (or uninstall and reinstall).

**Comment by ew0k** [comment]
this would be excellent

**Comment by elliotkillick** [comment]
Good idea! I've added documentation for this in https://github.com/elliotkillick/qvm-create-windows-qube/commit/4e07e4b5c76f7b558b569360e2cb52b4542c8431.

In the future, this will be streamlined so you can update Qvm-Create-Windows-Qube with a single `sudo qubes-dom0-update` command like any other Qubes package.
