### ISSUE TITLE
Windows 10 w/ 3840x2160 resolution?

### ISSUE THREAD

**Issue by secnice** [elliotkillick/qvm-create-windows-qube#49]
I've setup windows 7 and 10 both working all right, however I've noticed that windows 7 on a maximized window gets 3832x2077 resolution and when I go full screen it automatically goes to 3840x2160 which is my dom0 resolution.

On Windows 10 though it gets 2560x1600 on a maximized window and when I go full-screen it doesn't change like it does with Windows 7. This is sort of half the screen and a little ugly to work with.

How would one change the windows 10 resolution to at least 3832x2077 ?

**Comment by elliotkillick** [comment]
Please refer to this Hacker News comment to add support for arbitrary resolutions into SeaBIOS: https://news.ycombinator.com/item?id=28900125#28904084

**Comment by secnice** [comment]
Thank you very much!!! Finally got 4k 3840x2160 resolution working on windows 10!
This was pretty hard to do, spent a few days on it and it finally worked!
Again, Thank you very much for your work with this fantastic tool!
