### ISSUE TITLE
4.1 still intended?

### ISSUE THREAD

**Issue by ddevz** [elliotkillick/qvm-create-windows-qube#52]
The documentation says "A more streamlined and secure installation process with packaging will be shipping with Qubes R4.1", but they have already released "release candidate 3" for 4.1 (4.1.0-rc3), which does not seem to include qvm-create-windows-qube.  Is this sill intended to make it in before the 4.1 actual release?  (would be nice)

**Comment by github59173** [comment]
Any updates on this? Qubes 4.1 stable has been released.

**Comment by mercadolino** [comment]
Yes, that would be great. I am also looking forward for this to be available in 4.1. Still no native QWT available tough

**Comment by elliotkillick** [comment]
Unfortunately missed the R4.1 target. Apologies for my extended absence on this front while I was busy.

I do still want to get this packaged Qvm-Create-Windows-Qube packaged though. I'll see what I can do for R4.2 (ETA for its release?) but I can't make any commitments.

**Comment by brendanhoar** [comment]
> I do still want to get this packaged Qvm-Create-Windows-Qube packaged though. I'll see what I can do for R4.2 (ETA for its release?) but I can't make any commitments.

4.2.0-rc1 went out about a week ago.

B
