### ISSUE TITLE
Force to disable hibernation

### ISSUE THREAD

**Issue by jevank** [elliotkillick/qvm-create-windows-qube#53]
According to feedback from Qubes OS Forum it is critical to disable hibernation with Windows 10 at preparation stage. Looks like auto-qwt/run.bat is the place for it.

P.S. Very nice tool, thank you.

**Comment by brendanhoar** [comment]
@jevank - 

Would it make sense to have it be part of the general power_settings.bat execution in the crossbuild of QWT, modifying here:

https://github.com/QubesOS/qubes-installer-qubes-os-windows-tools/blob/master/power_settings.bat
```
:: Disable idle sleep & hibernation
powercfg /setacvalueindex SCHEME_MIN SUB_SLEEP STANDBYIDLE 0
powercfg /setdcvalueindex SCHEME_MIN SUB_SLEEP STANDBYIDLE 0
powercfg /setacvalueindex SCHEME_MIN SUB_SLEEP HIBERNATEIDLE 0
powercfg /setdcvalueindex SCHEME_MIN SUB_SLEEP HIBERNATEIDLE 0
```
By adding ```powercfg -H off``` or similar?

B

**Comment by jevank** [comment]
I've made changes in QWT-cross preparation.bat so this issue mostly for R4.0 users. But power_settings.bat looks more reasonable.

**Comment by elliotkillick** [comment]
We're already disabling hibernation in `optimize.bat` (it's at the end of the script). But it's good to have QWT doing it too now.
