### ISSUE TITLE
default debian-template

### ISSUE THREAD

**Issue by telepath** [elliotkillick/qvm-create-windows-qube#55]
Since Qubes 4.1 it's possible to use debian as default template for all qubes. The script assumes a fedora default template and fails if the management qube is created with a debian template.

I see two ways to solve this:
a) make having a fedora template a requisit and extend the script to find a suitable template (latest installed fedora template)
b) make the script compatible with debian as well as fedora, so it does not matter which template is default

Workaround:
For now, installing a fedora template and setting it as default for the first run of the script works fine.

**Comment by im7mortal** [comment]
There is actually part which handle it. It always was here.
https://github.com/elliotkillick/qvm-create-windows-qube/blob/master/install.sh#L101-L104

But it doesn't work. I faced today related error. 

I will try to debug it today after I am done with installation.

**Comment by im7mortal** [comment]
So when debian is default template is fails with
```
user@tmpl-for-debug:~$ sudo dnf -y install datefudge
Unable to detect release version (use '--releasever' to specify release version)
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```

Reason is that `command -v dnf` on bullseye debian-11 returns _/usr/bin/dnf_. 
Because [bullseye has dnf](https://packages.debian.org/bullseye/admin/dnf). But it fails because it needs additional set up.

@elliotkillick So there should be different condition to check if it's fedora or debian.

**Comment by im7mortal** [comment]
Tested fix for both standard templates
***FEDORA***
![FEDORA](https://user-images.githubusercontent.com/5336231/223003472-c8a44426-fee3-4de4-8d7e-3c8d4b92a14f.png)
***DEBIAN***
![DEBIAN](https://user-images.githubusercontent.com/5336231/223003506-0e847586-1180-4fe9-92f3-f1baf5ea6aaa.png)

I will create pull request shortly

**Comment by elliotkillick** [comment]
Yeah, definitely wasn't expecting Debian 11 to add the `dnf` command. This is fixed now.
