### ISSUE TITLE
geteltorito unavailable on Fedora 38

### ISSUE THREAD

**Issue by ideologysec** [ElliotKillick/qvm-create-windows-qube#68]
The `geteltorito` package is unavailable in Fedora 38 and appears to be considered orphaned. Hence, attempting to use any F38 templates will fail the install script.

Suggested workarounds:
- install a Fedora 37 template
- remove dependency on `geteltorito`

**Comment by ElliotKillick** [comment]
It looks `geteltorito`'s only package maintainer left. For it to become unorphaned someone would have to claim ownership: https://docs.fedoraproject.org/en-US/package-maintainers/Package_Orphaning_Process/#claiming_ownership_of_an_orphaned_package

After 6+ weeks of no maintainer an orphaned package becomes retired which is the state of the package now:
https://src.fedoraproject.org/rpms/geteltorito/blob/rawhide/f/dead.package
https://docs.fedoraproject.org/en-US/fesco/Policy_for_orphan_and_retired_packages/

The `geteltorito` script is pretty small so I think I may just import it into this repo directly.

**Comment by ElliotKillick** [comment]
This issue has been fixed: https://github.com/ElliotKillick/qvm-create-windows-qube/commit/5dce32cd2b6f3d2fb67b81f1d0615f38e01d8913
