### ISSUE TITLE
PGP Signature Verification

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [elliotkillick/qvm-create-windows-qube#7]
Hi,

The 'install.sh' script says to verify the PGP Signature, but it's not clear to me which file I'm verifying the PGP signature of, nor which key to verify it against.  Sorry if this seems like an asinine issue.

**Comment by elliotkillick** [comment]
The key line to look for is: `Good signature from "Elliot Killick <elliotkillick@zohomail.eu>"`. If it says that then the PGP signature has verified successfully.

Verifying the PGP signature out-of-band is just something I added as a paranoid security measure, you don't actually have to do that unless you want to. However, if you did want to do it then a basic way of going about doing that is looking for other places my PGP signature is posted publicly such as GitHub, mailing lists, https://keys.openpgp.org/, etc. and then just make sure my PGP signature/fingerprint (mine is `018F B9DE 6DFA 13FB 18FB 5552 F9B9 0D44 F83D D5F2`) matches up with the one in the example below. Again, only paranoid people need apply. :)

Example of a good signature:
```
[i] Please check for a good PGP signature (Verify it out-of-band if necessary)...
gpg: Signature made Sat Nov 30 07:48:44 2019 UTC
gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
gpg: Good signature from "Elliot Killick <elliotkillick@zohomail.eu>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 018F B9DE 6DFA 13FB 18FB  5552 F9B9 0D44 F83D D5F2
```

**Comment by elliotkillick** [comment]
I just simplified the message in 0caf0a38876fadddd0591d4d084c46ca5a778578. If people think they need to take the extra precaution then they will know to do it themselves, otherwise it just serves to confuse.

**Comment by e6lk7dqzm83p** [comment]
Hi,
I didn't get this content: 

> gpg: Signature made Sat Nov 30 07:48:44 2019 UTC
> gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
> gpg: Good signature from "Elliot Killick <elliotkillick@zohomail.eu>" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: 018F B9DE 6DFA 13FB 18FB  5552 F9B9 0D44 F83D D5F2

I get this output:

> Complete!
> [i] Shutting down fedora-30...
> [i] Cloning qvm-create-windows-qube GitHub repository...
> Cloning into 'qvm-create-windows-qube'...
> [i] Please check for a good PGP signature (Verify it out-of-band if necessary)..

Perhaps there's some larger issue (connected to #6 ).
