### ISSUE TITLE
qvm-create-windows-qube issues on Qubes 4.1 (Debian 11)

### ISSUE THREAD

**Issue by 4nthonyturn3r** [ElliotKillick/qvm-create-windows-qube#70]
I've installed the current `install.sh` script with up to date debian 11 template. Current version of QWT tool is 4.1.68.1.

Tested with win10x64 & win10x64-enterprise-ltsc-eval.

Command: `qvm-create-windows-qube -n sys-whonix -woy -i win10x64-enterprise-ltsc-eval.iso -a win10x64-enterprise-eval.xml anon-win10`
Error:
![image](https://github.com/ElliotKillick/qvm-create-windows-qube/assets/136760201/fafb1515-f888-48b2-963c-3e5cc443fbdf)

Have no clue how to solve the issue. Private Storage of `windows-mgmt` is 60GB.

**Comment by ElliotKillick** [comment]
The older `datefudge` that comes with Debian 11 doesn't support `--` (part of a recent precaution I added; only tested on Fedora).

Fixed: https://github.com/ElliotKillick/qvm-create-windows-qube/commit/e58a9b232f474e238fecef2ff3a44ed64deab73c

**Comment by 4nthonyturn3r** [comment]
Impressed, can confirm that it works now. Thank you for the fast bug fix.
