### ISSUE TITLE
Run mido.sh independently, unable to fetch .iso files with speficied tls options for curl

### ISSUE THREAD

**Issue by disbolog** [ElliotKillick/qvm-create-windows-qube#72]
I've used the `mido.sh` script independently to download an iso file.
 
Simply copy-pasted the content, run `chmod +x` and `./mido.sh win10x64-enterprise-ltsc-eval`.

It erred with the following message:
```
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
[!] Server returned an error status!

[!] 1 download(s) failed! Please re-run Mido with these arguments to attempt downloading again (any partial downloads will be resumed):  win10x64-enterprise-ltsc-eval
[+] Finished! Please see the above errors with information
```

I've then tried to simply replace all mentions of `--tlsv1.3` with `--tlsv1.2`, and with that was able to successfully pull the iso. `-tlsv1.1` did not work though.

My host system is Ubuntu 20.04.

Should this be of any concern?

**Comment by ElliotKillick** [comment]
It seems like`www.microsoft.com` (not `microsoft.com`) and `download.microsoft.com` dropped TLS 1.3 support:

```
$ curl --tlsv1.3 https://www.microsoft.com
curl: (35) OpenSSL/3.0.9: error:0A00042E:SSL routines::tlsv1 alert protocol version
```
We now only try to do the file downloads themselves (modern downloads pull from `software.download.prss.microsoft.com` or `software-static.download.prss.microsoft.com`) over TLS 1.3 as it's still supported there: 6ce27de4e11ffd316505ec356f48ef756fe758b7

Can also verify on SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=www.microsoft.com&latest
