### ISSUE TITLE
Disabled Windows Defender

### ISSUE THREAD

**Issue by alvaro652** [ElliotKillick/qvm-create-windows-qube#74]
Hi!

After creating a Windows 10 template VM, Windows Security shows this message under Virus & threat protection:

"Your Virus & threat protection is managed by your organization.
No active antivirus provider. Your device is vulnerable."

Under Security providers, it says:

"Microsoft Defender Antivirus is turned off."

Is this intended behaviour? How can i revert this? I have looked for modified group policies and did not find any.
Thank you

**Comment by alvaro652** [comment]
Found out there was a regristry key called DisableAntiSpyware under Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender.
Deleting this key reactivated windows defender.

**Comment by ElliotKillick** [comment]
This is done intentionally in `optimize.bat`. Windows Defender is a resource hog and fake security. If you're on Qubes OS, I assume you value the key real security principle employed by Qubes OS over that: **security through isolation**

I've contributed to Wikipedia why anti-malware software ultimately doesn't work and won't ever work: https://en.wikipedia.org/wiki/Security_through_obscurity#Criticism

> One of the largest proponents of security through obscurity commonly seen today is anti-malware software. What has followed is an infinite [cat-and-mouse game](https://en.wikipedia.org/wiki/Cat-and-mouse_game) of attackers finding new ways to avoid detection and defenders coming up with increasingly contrived but secret signatures to flag on.[[10]](https://en.wikipedia.org/wiki/Security_through_obscurity#cite_note-10)

Anti-malware software will only stop garden variety malware, script kiddies, and technically uninformed bad guys. Then give you false positives along with a false sense of security. That's it.
