### ISSUE TITLE
Script breaks while installing

### ISSUE THREAD

**Issue by ToneXum** [ElliotKillick/qvm-create-windows-qube#75]
### What happens:
When I'm installing Windows 10 x64 the installation gets stuck and does nothing after a while.

I see this line in my terminal:
`Installing Qubes Windows Tools...`

...and a batch script on my Desktop in the VM called `waiting_for_shutdown.bat`.

Nothing happened for half an hour so I decided to reboot the VM (I am aware that this might be a bad idea).

The terminal then prints out: `Completing setup of Qubes Windows Tools...` and nothing happens from there, most notably the networking "air gap" is never closed. 

### To reproduce:
- Download Win10x64 image using `mido.sh`
- Copy image to `windows-mgmt` into `/home/user/qvm-create-windows-qube/windows/isos`
- Start installation process

Flags:
- -n sys-firewall
- -oy
- -a win10x64-pro.xml

The qube is just called `windows`

**Comment by anon2507** [comment]
I have same issue while installing win10x64-enterprise-ltsc-eval.iso 
at ``` Installing Qubes Windows Tools... ```

and on windows-vm network problem
I used this command ``` qvm-create-windows-qube -n sys-firewall -oy -i win10x64-enterprise-ltsc-eval.iso -a win10x64-enterprise-ltsc-eval.xml work-win10s ```
and tried this also ``` qvm-create-windows-qube -n sys-firewall -oyp firefox,notepadplusplus,office365proplus -i win10x64-enterprise-ltsc-eval.iso -a win10x64-enterprise-ltsc-eval.xml work-win10 ```
I have same issue

can anybody help me to fix this?

**Comment by CameronCarranza** [comment]
I ran into this a few days ago as well, last comment here is me and what I had to do to get it to work properly hopefully resolves both of your issues. Not sure why we have to fetch a newer copy of Windows Tools but seems to be the cause 

[https://forum.qubes-os.org/t/qvm-create-windows-qube-qubes-windows-tools-install-hangs-infinitely/9851/17](https://forum.qubes-os.org/t/qvm-create-windows-qube-qubes-windows-tools-install-hangs-infinitely/9851/17)

**Comment by ToneXum** [comment]
Thanks, that worked!

**Comment by ElliotKillick** [comment]
Yep, this is not my bug. Triggered by the QSB advisory. The Qubes team should release a new QWT in time but until then, do be aware of the risks.

**Comment by ideologysec** [comment]
New versions of Qubes Windows Tools are coming in Qubes 4.3 (which is at RC1 currently).

https://github.com/QubesOS/qubes-issues/issues/1861
