### ISSUE TITLE
Permissions to mido.sh not granted

### ISSUE THREAD

**Issue by Middenvaus** [ElliotKillick/qvm-create-windows-qube#76]
[i] Please check for a "Good signature" from GPG (Verify it out-of-band if necessary)...
gpg: directory '/home/user/.gnupg' created
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
gpg: key F9B90D44F83DD5F2: public key "Elliot Killick <elliotkillick@zohomail.eu>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Sat Nov 30 09:48:44 2019 IST
gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
gpg: Good signature from "Elliot Killick <elliotkillick@zohomail.eu>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 018F B9DE 6DFA 13FB 18FB  5552 F9B9 0D44 F83D D5F2
[i] Remember to download the desired version(s) of Windows using Mido in the windows-mgmt qube...
/bin/bash: line 1: /home/user/qvm-create-windows-qube/windows/isos/mido.sh: Permission denied
[!] An unexpected error has occurred! Exiting...

**Comment by Middenvaus** [comment]
I have been already fix this myself  by ```chmod +x /home/user/qvm-create-windows-qube/windows/isos/mido.sh```

**Comment by NipponBill** [comment]
> I have been already fix this myself by `chmod +x /home/user/qvm-create-windows-qube/windows/isos/mido.sh`

@Middenvaus did you add this to `install.sh`?

**Comment by Middenvaus** [comment]
> NipponBill

no, i manualy run it in win-mgmt

**Comment by NipponBill** [comment]
@Middenvaus so then you also do the remaining steps in the script manually? 

I believe you miss the "air gapping" and "Copying qvm-create-windows-qube main program to Dom0" at this stage where the `install.sh` script fails.

**Comment by ElliotKillick** [comment]
My bad, I missed adding execution permission to `mido.sh` after copying it over from the [standalone Mido project](https://github.com/ElliotKillick/Mido). This has been fixed.
