### ISSUE TITLE
Unable to connect hardware to Windows VMs

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [elliotkillick/qvm-create-windows-qube#8]
Hi,
I was unable to connect a USB printer/scanner to Windows.  This may be an issue/limitation with Qubes Windows Tools.

**Comment by elliotkillick** [comment]
This is correct unless you have an entire PCI USB controller that you can assign to the Windows qube.

"USB passthrough to Windows qubes"
https://www.qubes-os.org/gsoc/

**Comment by mfp20** [comment]
PCIe devices can't be assigned as well. I get a whole system freeze on VM start. See issue [5603](https://github.com/QubesOS/qubes-issues/issues/5603).

**Comment by brendanhoar** [comment]
I’m generally able to assign a usb 3.0 pci controller device to a win7 hvm w/4GB RAM and it is stable on most boots.
