### ISSUE TITLE
Unable to adjust RAM allocation for Windows VM via Qubes GUI

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [elliotkillick/qvm-create-windows-qube#9]
I noticed in the Qubes Manager that I'm unable to increase the maximum RAM for my Windows VM. Is this by design?  Should we do adjustments via CLI?

**Comment by elliotkillick** [comment]
This is by design. Qubes Memory Manager (qmemman) is currently unstable in Windows.

https://github.com/crazyqube/qvm-create-windows-qube/issues/5

**Comment by e6lk7dqzm83p** [comment]
Ah ok.  Is it possible to do adjustments via CLI?

**Comment by elliotkillick** [comment]
Yes, but the experience will be unstable. Expect crashing.

**Comment by e6lk7dqzm83p** [comment]
Ah ok, is there a parameter we can pass to the script that would specify the memory we want on creation?

**Comment by elliotkillick** [comment]
No, once the Windows qube is done being created just do this in Dom0:
`qvm-prefs <windows_qube> maxmem <desired_max_mem>`

This will also allow you to change the setting in Qubes Manager.
